;.......................................................................
; Resource IDs
IDI_ICON    equ 100

IDD_DLG     equ 200
IDD_INF     equ 201

IDC_IMG     equ 300

IDE_NAME    equ 400
IDE_SERIAL  equ 401
IDE_RANDOM  equ 402
IDE_INF     equ 403

IDB_GEN     equ 410
IDB_CLOSE   equ 411
IDB_INF     equ 412
IDB_CLSINF  equ 413

IDR_INF     equ 500
IDR_REL     equ 501
IDR_RGN     equ 502

IDR_MUS     equ 600